### ISSUE TITLE
'pyunpack' requirement

### ISSUE THREAD

**Issue by Bondle** [Semi-Colin/chortle#1]
Hey there, on intial setup, Python doesn't come with pyunpack, newer users of Python might be confused, you might want to create a dependency management in your project with pyunpack to install the packages needed.

Right now, the way I fixed this was by installing pyunpack via pip. For future reference to anyone wanting to fix this, the command is:

`pip install pyunpack`

**Comment by semilin** [comment]
Thanks for the noticing, my new changes should have hopefully fixed this. 

I'll keep this open until it works for you.

**Comment by semilin** [comment]
I just tested this on a system without python for the new update, and this error no longer occurs.
